services:
  - type: web
    name: nadgorizontom
    runtime: static
    buildCommand: ""
    staticPublishPath: ./
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*.glb
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.js
        name: Cache-Control
        value: public, max-age=3600
      - path: /*.css
        name: Cache-Control
        value: public, max-age=3600
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
