services:
  - type: web
    name: nadgorizontom
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
